version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
    groups:
      actions:
        patterns: ['*']
  - package-ecosystem: github-actions
    directory: /actions/checkout-spec
    schedule:
      interval: monthly
    groups:
      actions:
        patterns: ['*']
